# Generated by Django 3.2.25 on 2024-10-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20241023_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='head2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
